import type {ScheduledSession} from '@/types.ts';
import {showSuccess, showWarning} from '@/lib/toastTheme.tsx';

export function exportICS(sessions: ScheduledSession[], today: string) {
    if (!sessions || sessions.length === 0) {
        showWarning("No Sessions", "No scheduled sessions to export.");
        return;
    }

    let icsContent = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AI Pilot Daily Timetable//EN\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\n";

    sessions.forEach((session, idx) => {
        const startStr = new Date(session.startTime).toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
        const endStr = new Date(session.endTime).toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
        const createdStr = new Date().toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";

        icsContent += "BEGIN:VEVENT\r\n";
        icsContent += `UID:session-${idx}-${Date.now()}@aipilot.ai\r\n`;
        icsContent += `DTSTAMP:${createdStr}\r\n`;
        icsContent += `DTSTART:${startStr}\r\n`;
        icsContent += `DTEND:${endStr}\r\n`;
        icsContent += `SUMMARY:${session.taskTitle.replace(/,/g, "\\,")}\r\n`;
        icsContent += "DESCRIPTION:Deep work session generated by AI Pilot Autonomous Planner.\r\n";
        icsContent += "STATUS:CONFIRMED\r\n";
        icsContent += "SEQUENCE:0\r\n";
        icsContent += "END:VEVENT\r\n";
    });

    icsContent += "END:VCALENDAR\r\n";

    const blob = new Blob([icsContent], {type: "text/calendar;charset=utf-8"});
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `timetable-${today}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showSuccess("Export Ready", "Calendar file (.ics) downloaded! You can import this into Google Calendar or Apple Calendar.");
}
