import type {ScheduledSession} from '@/types.ts';
import {showSuccess, showWarning, showError} from '@/lib/toastTheme.tsx';
import {formatTime, formatDateLong} from '@/lib/time.ts';

function getSessionExportStatus(session: ScheduledSession, completedTaskIds: Set<string>): {
    isCompleted: boolean;
    isNotAttended: boolean;
    statusText: string;
    statusClass: string
} {
    const isCompleted = session.completed || (session.taskId ? completedTaskIds.has(session.taskId) : false);
    const isSessPast = new Date() > new Date(session.endTime);
    const isNotAttended = isSessPast && !isCompleted && !session.started;
    const statusText = isCompleted ? "Completed" : isNotAttended ? "Not Attended" : "Scheduled";
    const statusClass = isCompleted ? "status-completed" : isNotAttended ? "status-notattended" : "status-scheduled";
    return {isCompleted, isNotAttended, statusText, statusClass};
}

const getLocalDateString = () => formatDateLong(new Date().toISOString());

export function exportDoc(sessions: ScheduledSession[], today: string, completedTaskIds: Set<string>) {
    if (!sessions || sessions.length === 0) {
        showWarning("No Sessions", "No scheduled sessions to export.");
        return;
    }

    const dateStr = getLocalDateString();
    let html = `
  <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
  <head>
    <title>Daily Timetable - ${dateStr}</title>
    <style>
      body { font-family: 'Segoe UI', Arial, sans-serif; color: #333333; margin: 40px; }
      h1 { color: #4f46e5; font-size: 24pt; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 5px; }
      .subtitle { color: #64748b; font-size: 11pt; margin-bottom: 30px; font-style: italic; }
      table { width: 100%; border-collapse: collapse; margin-top: 20px; }
      th { background-color: #f1f5f9; color: #334155; text-align: left; padding: 12px; font-weight: bold; border-bottom: 2px solid #cbd5e1; }
      td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 10pt; }
      .time { font-family: Consolas, monospace; font-weight: bold; color: #4f46e5; width: 150px; }
      .title { font-weight: 600; color: #0f172a; }
      .status { font-size: 9pt; text-transform: uppercase; font-weight: bold; letter-spacing: 0.5px; }
      .status-completed { color: #16a34a; }
      .status-scheduled { color: #4f46e5; }
      .status-notattended { color: #dc2626; }
      .footer { margin-top: 50px; font-size: 9pt; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px; }
    </style>
  </head>
  <body>
    <h1>AI Pilot — Daily Timetable</h1>
    <div class="subtitle">Generated Schedule for ${dateStr}</div>
    <table>
      <thead>
        <tr>
          <th>Time Slot</th>
          <th>Task/Session Title</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
`;

    sessions.forEach(session => {
        const {isCompleted, isNotAttended, statusText, statusClass} = getSessionExportStatus(session, completedTaskIds);

        html += `
        <tr>
          <td class="time">${formatTime(session.startTime)} - ${formatTime(session.endTime)}</td>
          <td class="title">${session.taskTitle}</td>
          <td class="status ${statusClass}">${statusText}</td>
        </tr>
  `;
    });

    html += `
      </tbody>
    </table>
    <div class="footer">
      Generated by AI Pilot Assistant on ${new Date().toLocaleString()}
    </div>
  </body>
  </html>
`;

    const blob = new Blob(['\ufeff' + html], {type: 'application/msword;charset=utf-8'});
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `timetable-${today}.doc`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showSuccess("Export Ready", "Word Document (.doc) downloaded! Perfect for offline reference or import into Google Docs.");
}

export function printTimetable(sessions: ScheduledSession[], completedTaskIds: Set<string>) {
    if (!sessions || sessions.length === 0) {
        showWarning("No Sessions", "No scheduled sessions to print.");
        return;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        showError("Pop-up Blocked", "Pop-up blocker is preventing the printable view from opening. Please allow popups for this site.");
        return;
    }

    const dateStr = getLocalDateString();
    let itemsHtml = '';
    sessions.forEach(session => {
        const {isCompleted, isNotAttended} = getSessionExportStatus(session, completedTaskIds);
        itemsHtml += `
    <div class="item ${isCompleted ? 'completed' : ''} ${isNotAttended ? 'notattended' : ''}">
      <div class="time-block">
        <div class="time">${formatTime(session.startTime)}</div>
        <div class="time-end">${formatTime(session.endTime)}</div>
      </div>
      <div class="info">
        <div class="title">${session.taskTitle}</div>
        <div class="status">${isCompleted ? '✓ Completed' : isNotAttended ? '○ Not Attended' : '○ Scheduled'}</div>
      </div>
    </div>
  `;
    });

    printWindow.document.write(`
  <html>
    <head>
      <title>Print Daily Timetable - ${dateStr}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          color: #1a202c;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        header {
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        h1 {
          font-size: 28px;
          font-weight: 300;
          margin: 0;
          color: #4c51bf;
        }
        .date {
          font-size: 14px;
          color: #718096;
          margin-top: 5px;
        }
        .list {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }
        .item {
          display: flex;
          padding: 15px;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          align-items: center;
        }
        .item.completed {
          background-color: #f0fff4;
          border-color: #c6f6d5;
          opacity: 0.8;
        }
        .item.completed .title {
          text-decoration: line-through;
          color: #4a5568;
        }
        .item.notattended {
          background-color: #fef2f2;
          border-color: #fecaca;
          opacity: 0.7;
        }
        .item.notattended .status {
          color: #dc2626;
        }
        .time-block {
          width: 120px;
          font-family: monospace;
          font-weight: bold;
          font-size: 14px;
          border-right: 2px solid #edf2f7;
          padding-right: 15px;
          margin-right: 15px;
        }
        .time-end {
          font-size: 11px;
          color: #718096;
          font-weight: normal;
        }
        .info {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-grow: 1;
          gap: 20px;
        }
        .title {
          font-size: 16px;
          font-weight: 500;
          flex-grow: 1;
          line-height: 1.4;
        }
        .status {
          font-size: 12px;
          font-weight: bold;
          text-transform: uppercase;
          color: #4c51bf;
          white-space: nowrap;
          flex-shrink: 0;
        }
        .completed .status {
          color: #38a169;
        }
        footer {
          margin-top: 60px;
          text-align: center;
          font-size: 12px;
          color: #a0aec0;
          border-top: 1px solid #e2e8f0;
          padding-top: 20px;
        }
        @media print {
          body { padding: 20px; }
          button { display: none; }
        }
        .no-print {
          background: #4c51bf;
          color: white;
          border: none;
          padding: 10px 20px;
          border-radius: 6px;
          font-weight: bold;
          cursor: pointer;
          margin-bottom: 20px;
        }
      </style>
    </head>
    <body>
      <button class="no-print" onclick="window.print()">Print This Timetable</button>
      <header>
        <h1>AI Pilot — Daily Timetable</h1>
        <div class="date">${dateStr}</div>
      </header>
      <div class="list">
        ${itemsHtml}
      </div>
      <footer>
        Generated by AI Pilot Assistant
      </footer>
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
          }, 500);
        }
      </script>
    </body>
  </html>
`);
    printWindow.document.close();
}
